### ISSUE TITLE
JVM version detection breaks on Java 10

### ISSUE THREAD

**Issue by perlun** [jruby/jruby-openssl#157]
Very similar to #142; this has unfortunately regressed on Java 10.

```shell
$ gem install bundler
Ignoring executable-hooks-1.4.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.4.2
Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
Ignoring jruby-launcher-1.1.4-java because its extensions are not built.  Try: gem pristine jruby-launcher --version 1.1.4
Error loading RubyGems plugin "/Users/plundberg/.rvm/gems/jruby-9.1.16.0@global/gems/executable-hooks-1.4.2/lib/rubygems_plugin.rb": no such file to load -- executable-hooks/wrapper (LoadError)
Error loading RubyGems plugin "/Users/plundberg/.rvm/gems/jruby-9.1.16.0@global/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb": no such file to load -- gem-wrappers (LoadError)
ERROR:  Loading command: install (LoadError)
	load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

The reason why this has reappeared is because the `java.version` format has been changed upstream (_again_.... 😄)

```shell
$ java9
$ java -XshowSettings 2>&1 | grep java.version
    java.version = 9.0.4
$ java10
$ java -XshowSettings 2>&1 | grep java.version
    java.version = 10
    java.version.date = 2018-03-20
```

I.e. the fix in #143 is really needed for us to get working on Java 10, unless the OpenJDK team is willing to change the version to a normal SemVer version string again. (which I personally think makes sense, but I don't have the full picture there to be able to speak dogmatically about the matter.) Anyhow, going back and forth like this does not make a whole lot of sense to me.

**Comment by headius** [comment]
Sigh.

**Comment by headius** [comment]
I am just going to hardcode it to use V9 for anything that isn't "1.7", "1.8", or "8". Hopefully they'll settle into a pattern before we decide we need Java 10 bytecode features.

**Comment by headius** [comment]
I've fixed this on all branches of JRuby and it will be in the next releases, whatever they may be.

**Comment by perlun** [comment]
Much appreciated @headius, thank you for this.

**Comment by headius** [comment]
@kares We need to get a release out for 9.1.17. Do you have anything else you want to get in?

**Comment by perlun** [comment]
Java 10.0.1 has been released and they have sorted this out now:

```
$ java -XshowSettings 2>&1 | grep java.version
    java.version = 10.0.1
    java.version.date = 2018-04-17
$ gem install bundler
Successfully installed bundler-1.16.1
1 gem installed
```

I will close this issue now. If someone feels like it should still be open for whatever reason, feel free to reopn.

**Comment by kares** [comment]
has been resolved in jruby-openssl (>=) **0.10.0**. 
only Java (9/10) pre-releases were really problematic, as comments already suggested.

**Comment by eiswind** [comment]
I still see this broken withjava 11 and 9.1.17.0, it seems to be ok with 9.2.0.0 but unfortunately I need 9.1. for asciidoctorj.

**Comment by Seegras** [comment]
Still broken here:

bin/logstash
unsupported Java version "10", defaulting to 1.7

java -XshowSettings 2>&1 | grep java.version
    java.version = 10.0.2
    java.version.date = 2018-07-17

dpkg -l | grep logstash 
logstash                              1:6.5.0-1 

Would you please at least get rid of the stupid check and just *try* to take whatever java is offered? because it just might work; whereas defaulting to ancient versions sure does not.

**Comment by schwaz80** [comment]
> Still broken here:
> 
> bin/logstash
> unsupported Java version "10", defaulting to 1.7
> 
> java -XshowSettings 2>&1 | grep java.version
> java.version = 10.0.2
> java.version.date = 2018-07-17
> 
> dpkg -l | grep logstash
> logstash 1:6.5.0-1
> 
> Would you please at least get rid of the stupid check and just _try_ to take whatever java is offered? because it just might work; whereas defaulting to ancient versions sure does not.

This still looks broken. I am running a slightly newer version of Logstash and still seeing the same errors.

**Comment by sumanawal** [comment]
I am still getting this error in java version 12.

```
$ gem install bundler
ERROR:  Loading command: install (LoadError)
	load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
$ java -XshowSettings 2>&1 | grep java.version
    java.version = 12
    java.version.date = 2019-03-19
```

**Comment by yumao5** [comment]
> I am still getting this error in java version 12.
> 
> ```
> $ gem install bundler
> ERROR:  Loading command: install (LoadError)
> 	load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
> ERROR:  While executing gem ... (NoMethodError)
>     undefined method `invoke_with_build_args' for nil:NilClass
> $ java -XshowSettings 2>&1 | grep java.version
>     java.version = 12
>     java.version.date = 2019-03-19
> ```

Same here.
